env: prod
http:
  port: 8000
data:
  mysql:
    user: user:password@tcp(demo_db:3306)/course_management?charset=utf8mb4&parseTime=True&loc=Local

log:
  log_level: info
  encoding: json           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30              # 日志文件最多保存多少个备份
  max_age: 7                   #  文件最多保存多少天
  max_size: 1024               #  每个日志文件保存的最大尺寸 单位：M
  compress: true               # 是否压缩