// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"course-sign-up/internal/handler"
	"course-sign-up/internal/repository"
	"course-sign-up/internal/server"
	"course-sign-up/internal/service"
	"course-sign-up/pkg/log"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	db := repository.NewDb(viperViper)
	repositoryRepository := repository.NewRepository(logger, db)
	courseRepository := repository.NewCourseRepository(repositoryRepository)
	courseService := service.NewCourseService(serviceService, courseRepository)
	courseHandler := handler.NewCourseHandler(handlerHandler, courseService)
	engine := server.NewServerHTTP(logger, courseHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewDb, repository.NewRepository, repository.NewCourseRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewCourseService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewCourseHandler)
